version: '3.8'
services:
  app:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    command: bash -lc "pip install -r requirements.txt && python async_trader.py"
    restart: always

